### ISSUE TITLE
application-role-index.js file

### ISSUE THREAD

**Issue by tifa2100** [Robynhu/AspNetCore.Identity.PostgreSQL#10]
Hi,

I am searching for this file "application-role-index.js" as ApplicationRole/Index.cshtml using it.

Thanks in advance.

**Comment by robson-paproski** [comment]
Sorry for the delay in answering you @tifa2100, the file is missing from the example, sorry for that, gonna check it.. But the main point of this example was to show how can use the lib to connect to a postgresql database. Please let me know if i can help you in anyway :)
