### ISSUE TITLE
How to use the AspNetCore.Identity.PostgreSQL in Blazor Server app? 

### ISSUE THREAD

**Issue by win32nipuh** [Robynhu/AspNetCore.Identity.PostgreSQL#18]
I'd like to replace the Login/Logoff implementation with this AspNetCore.Identity.PostgreSQL.
At least it does not use EF with migrations etc.

How to use it in Blazor app? Is it possible to provide a little example? Thnx.

**Comment by ZedZipDev** [comment]
Ok, it is solved. You can delete this issue.

**Comment by robson-paproski** [comment]
👍
