### ISSUE TITLE
Create a nuget package and upgrade to .net core 2

### ISSUE THREAD

**Issue by xabikos** [Robynhu/AspNetCore.Identity.PostgreSQL#4]
Hello @Robynhu 

Thanks for the amazing project. I have two questions though. 
1. Is there any plan to create and publish a nuget package in order to make it easier to use it from an application.
2. What about upgrading and using the latest .net core 2 bits?

**Comment by robson-paproski** [comment]
Hello @xabikos 
Thank you for the questions :), Let's go to the answers

1 - Yes, already have actualy https://www.nuget.org/packages/AspNetCore.Identity.PostgreSQL.dll/ 

2 - I didn't tested with .net core 2 yet, but i'm planning to do so as soon as i can. I believe in one or two weeks tops.

If you have more questions please feel free to ask

**Comment by xabikos** [comment]
Thanks for the ultra quick reply. 

I will be waiting for the update to .net core 2.

**Comment by xabikos** [comment]
FYI when tried to install the existing package from a .net standard 2 application I got the following error 
```
info :   CACHE https://api.nuget.org/v3-flatcontainer/aspnetcore.identity.postgresql.dll/index.json
error: Package Microsoft.NETCore.App 1.1.2 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.NETCore.App 1.1.2 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
error: Package 'AspNetCore.Identity.PostgreSQL.dll' is incompatible with 'all' frameworks in project 'C:\Development\GreatSpeakers\projects\GreatSpeakers.Domain\GreatSpeakers.Domain.csproj'.
```

So I guess it's required to upgrade and release a new nugget version in order to use it from the latest .net core.

Side note: I am not sure if it's possible but if you could remove the last `.dll` from the package name would be awesome.

**Comment by robson-paproski** [comment]
As soon as i complete the update and correct the nuget package, i will close and update this issue.

Thanks for the feedback.

**Comment by robson-paproski** [comment]
@xabikos 
Just updated to .Net Core 2.0, with support to .Net Standard 2.0.

I will review the steps in Readme.md tomorrow, but i want you to know that i just publish new package to Nuget.
https://www.nuget.org/packages/AspNetCore.Identity.PostgreSQL.dll/

As always, feel free to ask in case of doubt. If you wanna contribuite to the project, also feel free to. I love feedbacks =D hehehe

**Comment by xabikos** [comment]
@Robynhu thanks for spending time on that. 

I have some feedback though. When I tried to install the nugget package from a `.netstandard2.0` class library  I got an error. This is caused because the published nuget package requires a `netcoreapp2.0` app.

I spent some time looking into the source code of the project and found out that you have already a project that targets the `netstandard2.0`. If I am not mistaken the two projects contain the same source code but targeting different framework/platform. I think the one targets the `netcoreapp2.0` is useless as all applications can reference `netstandard2.0` packages but not the other way around. So please make sure you publish the `netstandard2.0` project in nuget. 

Another small change you could do is to remove one section in `csproj` file. More specifically the section 
```
<ItemGroup>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.configuration.abstractions\2.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>
```
Looks a bit weird to me this reference. I removed it and the project builds without a problem. So I assume you could remove it in the next set of changes.
